site_name: RSMetaCheck
theme:
  name: material
extra_css:
  - stylesheets/mkdocs.css
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Output: output.md
  - Catalog: catalog.md
